### PR TITLE
Update EDA + Add Makefile to README

### LINKED ISSUE #44: Create Makefile
Write a Makefile (literally called Makefile) to act as a driver script to rule them all. This script should run the others in sequence, hard coding in the appropriate arguments. This script should:

- [x] Live in the project’s root directory and be named Makefile
- [x] Be well documented (using the project README and comments inside the Makefile to explain what it does and how to use it)
- [x] Have a all: target so that you can easily run the entire analysis from top to bottom by running make all at the command line
- [x] Have a clean: target so that you can easily “undo” your analysis by running make clean at the command line

### PR DESCRIPTION
**Pull request by gn385x**

### CODE REVIEW

**Comment by danfke** [comment]
Someone raised a good point in one of our peer reviews. All of the code is currently under `if __name__ == "__main__":`, could you instead just copy paste the code into a main function and then run the main function under `if __name__ == "__main__":`. See our other scripts for reference. Thanks @LG you did a lot of great work

**Comment by gn385x** [comment]
> Someone raised a good point in one of our peer reviews. All of the code is currently under `if __name__ == "__main__":`, could you instead just copy paste the code into a main function and then run the main function under `if __name__ == "__main__":`. See our other scripts for reference. Thanks @lg you did a lot of great work

good point. added!

**Review by iamMoid — APPROVED** [review]
Changes look good!

**Review by SiqiTao — APPROVED** [review]
looks good to me thanks @gn385x !

**Review by danfke — APPROVED** [review]
Thanks for addressing my concerns!

**Pull request merged**
