### PR TITLE
Update EDA

### LINKED ISSUE #3: EDA on NCDB data
Perform EDA on National Collision data using Altair

### PR DESCRIPTION
**Pull request by gn385x**
Below is the summary of the new changes I have made to the EDA:

1. Restructure the analysis in a clear and organized format
2. Add description to each step of the analysis
3. Add an EDA table
4. Create multiple EDA visualizations based on agreements from group meeting
5. Add a profile report using pandas-profiling

P/S: Thanks Moid for setting up the great groundwork!

### CODE REVIEW

**Review by danfke — COMMENTED** [review]
Really great work LG! My only comments are we should probably have a docstring for any functions we define, and the pandas profiling doesn't seem to render on Git Hub (not sure if that matters). Other than that the EDA was very eye-opening and I now understand our data a lot better.

**Review by danfke — CHANGES_REQUESTED** [review]
Actually I think there may be a pretty large error in the EDA that can thankfully be eeasily fixed (?) I don't think we should count the target class values and run .info() and .describe() on the data set before splitting. All of these should only be run on the training set.

**Review by iamMoid — COMMENTED** [review]
This looks very organized and insightful. In addition to Daniel's feedback, my only suggestion would be to fix the height and width of the charts in the function itself so that all of the charts are of the same shape and size.

**Comment by gn385x** [comment]
Thanks guys a lot for reviewing! 

@all 
I made some changes to the EDA script. Here are the main improvements:
1.  Use 'sort_index()' to get a view of the data from both head and tail
2. Apply target count + .info() + .describe() on training set only
3. Deal with missing values
4. Add a docstring for the function 'create_chart' I created in the script
5. Set uniform figure sizes
6. Make pandas-profiling report optional

@danfke 
- Docstring: I added the docstring - good catch!
- Pandas-profiling report: I did notice that the pandas profile report doesn't render well on GitHub (it looks nice on Jupyter Lab tho *sad*). I end up deciding to make the pandas-profiling report optional because the report is so heavy that it creates loading issues in GitHub. Whoever is interested in the report can uncomment and run my code on their own. 
- EDA table: Interestingly enough, in the example EDA, she did populate the count of the target class values before and after splitting the data - that's why I adopted it. That being said, I agree with you.. so to be safe, I do all the summary statistics on the train set only. 

@iamMoid 
- Figure size: I made the size of all charts uniform. Good point!

**Review by iamMoid — CHANGES_REQUESTED** [review]
First and foremost - Thank you for addressing previous feedback. Excellent job! It looks crisp and is put together well with the narration pieces between the codes!

I took a quick look and noticed two items:
1. We decided on a 90%-10% train-test data split and my initial EDA commit had a 10% split. I see a 20% split now. I think we should go back to 10% as this will give our model around 29K more rows to train on and will still leave us with another unseen 29k rows to test on.
2. A grammatical error under Pandas Profiling: `We make it optional because the code does took quite a while to run and not render well on GitHub.`  Can you update "took" to "take"?

**Comment by gn385x** [comment]
> First and foremost - Thank you for addressing previous feedback. Excellent job! It looks crisp and is put together well with the narration pieces between the codes!
> 
> I took a quick look and noticed two items:
> 
> 1. We decided on a 90%-10% train-test data split and my initial EDA commit had a 10% split. I see a 20% split now. I think we should go back to 10% as this will give our model around 29K more rows to train on and will still leave us with another unseen 29k rows to test on.
> 2. A grammatical error under Pandas Profiling: `We make it optional because the code does took quite a while to run and not render well on GitHub.`  Can you update "took" to "take"?

I changed test size from 20% to 10%. Also I fixed the grammatical error. Thank you!

**Review by iamMoid — APPROVED** [review]

**Review by danfke — APPROVED** [review]
Amazing work LG, thanks for addressing all of our concerns :)

**Comment by SiqiTao** [comment]
EDA looks great after the suggestions by @danfke and @iamMoid! Good job LG!

**Review by SiqiTao — COMMENTED** [review]
The overall EDA looks great to me after modifications suggested by @danfke  and @iamMoid . Thanks LG for the great work!

**Review by SiqiTao — APPROVED** [review]

**Pull request merged**
